GET {{product-service-endpoint}}/products
Content-Type: application/json

###

GET {{product-service-endpoint}}/products/search/product-id/11f2e86a-9d5d-42f9-b3c2-3e4d652e3df89
Content-Type: application/json

###

GET {{product-service-endpoint}}/products/search/Apple
Content-Type: application/json 

###
POST {{product-service-endpoint}}/products
Content-Type: application/json

{
  "productName": "Executive Office Desk 2",
  "category": "Furniture",
  "unitPrice": 399.99,
  "quantityInStock": 20
}
###

PUT {{product-service-endpoint}}/products
Content-Type: application/json

{
  "productID": "88cb4583-e3ef-48e3-a113-1c6353fe677f",
  "productName": "Executive Office Desk 2",
  "category": "Furniture",
  "unitPrice": 359.99,
  "quantityInStock": 21
}
###

DELETE {{product-service-endpoint}}/products/88cb4583-e3ef-48e3-a113-1c6353fe677f
Content-Type: application/json

###
