POST {{user-service-endpoint}}/auth/register
Content-Type: application/json

{
    "PersonName": "newuser",
    "PasswordHash": "NewUser@123",
    "Email": "newuser@example.com",
    "Gender": "Male"
}

###

POST {{user-service-endpoint}}/auth/login
Content-Type: application/json

{
  "Email": "test1@example.com",
  "PasswordHash": "password1"
}
###

GET {{user-service-endpoint}}/c32f8b42-60e6-4c02-90a7-9143ab37189f
Content-Type: application/json

###