POST https://localhost:7012/api/auth/register
Content-Type: application/json

{
    "PersonName": "newuser",
    "Password": "NewUser@123",
    "Email": "newuser@example.com",
    "Gender": "Male"
}

###

POST https://localhost:7012/api/auth/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "NewUser@123"
}