POST http://localhost:9090/api/auth/register
Content-Type: application/json

{
    "PersonName": "newuser",
    "PasswordHash": "NewUser@123",
    "Email": "newuser@example.com",
    "Gender": "Male"
}

###

POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
  "Email": "newuser@example.com",
  "PasswordHash": "NewUser@123"
}
###

GET http://localhost:9090/api/users/d3c81539-949c-42c2-b3ca-495bddf4c811
Content-Type: application/json

###